controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    steering_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    publish_rate: 50

velocity_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_front_wheel_joint
      - right_front_wheel_joint
      - left_back_wheel_joint
      - right_back_wheel_joint

steering_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_front_steering_joint
      - right_front_steering_joint
      - left_back_steering_joint
      - right_back_steering_joint