slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: scan

    mode: mapping
    resolution: 0.05

    minimum_time_interval: 0.0
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05

    transform_publish_period: 0.02
    map_update_interval: 2.0

    use_scan_matching: true
    do_loop_closing: true
