controller_manager:
  ros__parameters:
    update_rate: 10
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    steering_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters: {}

# 4WD駆動制御
diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_front_wheel_joint", "left_back_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint", "right_back_wheel_joint"]
    
    wheel_separation: 0.8
    wheel_radius: 0.15
    
    use_stamped_vel: false
    publish_rate: 50.0
    
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    enable_odom_tf: true
    cmd_vel_timeout: 0.25
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

# ステアリング制御
steering_controller:
  ros__parameters:
    joints:
      - left_front_steering_joint
      - right_front_steering_joint
      - left_back_steering_joint
      - right_back_steering_joint