joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.02
    autorepeat_rate: 10.0

teleop_node:
  ros__parameters:
    enable_button: 5   # R1 は「許可」だけ

    # 右スティック上下 → 前後
    axis_linear:
      x: 4
    scale_linear:
      x: 0.8   # 上で前進になるよう反転

    # 左スティック左右 → ステア
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.8
